package si.uni_lj.fri.pbd.miniapp3.models;

import si.uni_lj.fri.pbd.miniapp3.database.entity.RecipeDetails;
import si.uni_lj.fri.pbd.miniapp3.models.dto.RecipeDetailsDTO;
import si.uni_lj.fri.pbd.miniapp3.models.dto.RecipeSummaryDTO;

public final class Mapper {

    public static RecipeSummaryIM mapRecipeDetailsToRecipeSummaryIm(RecipeDetails rec) {
        return new RecipeSummaryIM(rec.getStrMeal(), rec.getStrMealThumb(), rec.getIdMeal());
    }

    public static RecipeSummaryIM mapRecipeSummaryDtoToRecipeSummaryIm(RecipeSummaryDTO rec) {
        return new RecipeSummaryIM(rec.getStrMeal(), rec.getStrMealThumb(), rec.getIdMeal());
    }

    public static RecipeDetails mapRecipeDetailsImToRecipeDetails(RecipeDetailsIM rec, boolean isFavorite) {
        return new RecipeDetails(
                isFavorite,
                rec.getIdMeal(),
                rec.getStrMeal(),
                rec.getStrCategory(),
                rec.getStrArea(),
                rec.getStrInstructions(),
                rec.getStrMealThumb(),
                rec.getStrYoutube(),
                rec.getStrIngredient1(),
                rec.getStrIngredient2(),
                rec.getStrIngredient3(),
                rec.getStrIngredient4(),
                rec.getStrIngredient5(),
                rec.getStrIngredient6(),
                rec.getStrIngredient7(),
                rec.getStrIngredient8(),
                rec.getStrIngredient9(),
                rec.getStrIngredient10(),
                rec.getStrIngredient11(),
                rec.getStrIngredient12(),
                rec.getStrIngredient13(),
                rec.getStrIngredient14(),
                rec.getStrIngredient15(),
                rec.getStrIngredient16(),
                rec.getStrIngredient17(),
                rec.getStrIngredient18(),
                rec.getStrIngredient19(),
                rec.getStrIngredient20(),
                rec.getStrMeasure1(),
                rec.getStrMeasure2(),
                rec.getStrMeasure3(),
                rec.getStrMeasure4(),
                rec.getStrMeasure5(),
                rec.getStrMeasure6(),
                rec.getStrMeasure7(),
                rec.getStrMeasure8(),
                rec.getStrMeasure9(),
                rec.getStrMeasure10(),
                rec.getStrMeasure11(),
                rec.getStrMeasure12(),
                rec.getStrMeasure13(),
                rec.getStrMeasure14(),
                rec.getStrMeasure15(),
                rec.getStrMeasure16(),
                rec.getStrMeasure17(),
                rec.getStrMeasure18(),
                rec.getStrMeasure19(),
                rec.getStrMeasure20(),
                rec.getStrSource());
    }

    public static RecipeDetails mapRecipeDetailsDtoToRecipeDetails(Boolean isFavorite, RecipeDetailsDTO dto) {
        return new RecipeDetails(
                isFavorite,
                dto.getIdMeal(),
                dto.getStrMeal(),
                dto.getStrCategory(),
                dto.getStrArea(),
                dto.getStrInstructions(),
                dto.getStrMealThumb(),
                dto.getStrYoutube(),
                dto.getStrIngredient1(),
                dto.getStrIngredient2(),
                dto.getStrIngredient3(),
                dto.getStrIngredient4(),
                dto.getStrIngredient5(),
                dto.getStrIngredient6(),
                dto.getStrIngredient7(),
                dto.getStrIngredient8(),
                dto.getStrIngredient9(),
                dto.getStrIngredient10(),
                dto.getStrIngredient11(),
                dto.getStrIngredient12(),
                dto.getStrIngredient13(),
                dto.getStrIngredient14(),
                dto.getStrIngredient15(),
                dto.getStrIngredient16(),
                dto.getStrIngredient17(),
                dto.getStrIngredient18(),
                dto.getStrIngredient19(),
                dto.getStrIngredient20(),
                dto.getStrMeasure1(),
                dto.getStrMeasure2(),
                dto.getStrMeasure3(),
                dto.getStrMeasure4(),
                dto.getStrMeasure5(),
                dto.getStrMeasure6(),
                dto.getStrMeasure7(),
                dto.getStrMeasure8(),
                dto.getStrMeasure9(),
                dto.getStrMeasure10(),
                dto.getStrMeasure11(),
                dto.getStrMeasure12(),
                dto.getStrMeasure13(),
                dto.getStrMeasure14(),
                dto.getStrMeasure15(),
                dto.getStrMeasure16(),
                dto.getStrMeasure17(),
                dto.getStrMeasure18(),
                dto.getStrMeasure19(),
                dto.getStrMeasure20(),
                dto.getStrSource());
    }

    public static RecipeDetailsIM mapRecipeDetailsDtoToRecipeDetailsIm(Boolean isFavorite, RecipeDetailsDTO dto) {
        return new RecipeDetailsIM(isFavorite,
                dto.getIdMeal(),
                dto.getStrMeal(),
                dto.getStrCategory(),
                dto.getStrArea(),
                dto.getStrInstructions(),
                dto.getStrMealThumb(),
                dto.getStrYoutube(),
                dto.getStrIngredient1(),
                dto.getStrIngredient2(),
                dto.getStrIngredient3(),
                dto.getStrIngredient4(),
                dto.getStrIngredient5(),
                dto.getStrIngredient6(),
                dto.getStrIngredient7(),
                dto.getStrIngredient8(),
                dto.getStrIngredient9(),
                dto.getStrIngredient10(),
                dto.getStrIngredient11(),
                dto.getStrIngredient12(),
                dto.getStrIngredient13(),
                dto.getStrIngredient14(),
                dto.getStrIngredient15(),
                dto.getStrIngredient16(),
                dto.getStrIngredient17(),
                dto.getStrIngredient18(),
                dto.getStrIngredient19(),
                dto.getStrIngredient20(),
                dto.getStrMeasure1(),
                dto.getStrMeasure2(),
                dto.getStrMeasure3(),
                dto.getStrMeasure4(),
                dto.getStrMeasure5(),
                dto.getStrMeasure6(),
                dto.getStrMeasure7(),
                dto.getStrMeasure8(),
                dto.getStrMeasure9(),
                dto.getStrMeasure10(),
                dto.getStrMeasure11(),
                dto.getStrMeasure12(),
                dto.getStrMeasure13(),
                dto.getStrMeasure14(),
                dto.getStrMeasure15(),
                dto.getStrMeasure16(),
                dto.getStrMeasure17(),
                dto.getStrMeasure18(),
                dto.getStrMeasure19(),
                dto.getStrMeasure20(),
                dto.getStrSource());
    }

    public static RecipeDetailsIM mapRecipeDetailsToRecipeDetailsIm(Boolean isFavorite, RecipeDetails rec) {
        return new RecipeDetailsIM(
                isFavorite,
                rec.getIdMeal(),
                rec.getStrMeal(),
                rec.getStrCategory(),
                rec.getStrArea(),
                rec.getStrInstructions(),
                rec.getStrMealThumb(),
                rec.getStrYoutube(),
                rec.getStrIngredient1(),
                rec.getStrIngredient2(),
                rec.getStrIngredient3(),
                rec.getStrIngredient4(),
                rec.getStrIngredient5(),
                rec.getStrIngredient6(),
                rec.getStrIngredient7(),
                rec.getStrIngredient8(),
                rec.getStrIngredient9(),
                rec.getStrIngredient10(),
                rec.getStrIngredient11(),
                rec.getStrIngredient12(),
                rec.getStrIngredient13(),
                rec.getStrIngredient14(),
                rec.getStrIngredient15(),
                rec.getStrIngredient16(),
                rec.getStrIngredient17(),
                rec.getStrIngredient18(),
                rec.getStrIngredient19(),
                rec.getStrIngredient20(),
                rec.getStrMeasure1(),
                rec.getStrMeasure2(),
                rec.getStrMeasure3(),
                rec.getStrMeasure4(),
                rec.getStrMeasure5(),
                rec.getStrMeasure6(),
                rec.getStrMeasure7(),
                rec.getStrMeasure8(),
                rec.getStrMeasure9(),
                rec.getStrMeasure10(),
                rec.getStrMeasure11(),
                rec.getStrMeasure12(),
                rec.getStrMeasure13(),
                rec.getStrMeasure14(),
                rec.getStrMeasure15(),
                rec.getStrMeasure16(),
                rec.getStrMeasure17(),
                rec.getStrMeasure18(),
                rec.getStrMeasure19(),
                rec.getStrMeasure20(),
                rec.getStrSource());
    }

    public static RecipeDetailsIM mapRecipeDetailsToRecipeDetailsIm(RecipeDetails rec) {
        return new RecipeDetailsIM(
                rec.getFavorite(),
                rec.getIdMeal(),
                rec.getStrMeal(),
                rec.getStrCategory(),
                rec.getStrArea(),
                rec.getStrInstructions(),
                rec.getStrMealThumb(),
                rec.getStrYoutube(),
                rec.getStrIngredient1(),
                rec.getStrIngredient2(),
                rec.getStrIngredient3(),
                rec.getStrIngredient4(),
                rec.getStrIngredient5(),
                rec.getStrIngredient6(),
                rec.getStrIngredient7(),
                rec.getStrIngredient8(),
                rec.getStrIngredient9(),
                rec.getStrIngredient10(),
                rec.getStrIngredient11(),
                rec.getStrIngredient12(),
                rec.getStrIngredient13(),
                rec.getStrIngredient14(),
                rec.getStrIngredient15(),
                rec.getStrIngredient16(),
                rec.getStrIngredient17(),
                rec.getStrIngredient18(),
                rec.getStrIngredient19(),
                rec.getStrIngredient20(),
                rec.getStrMeasure1(),
                rec.getStrMeasure2(),
                rec.getStrMeasure3(),
                rec.getStrMeasure4(),
                rec.getStrMeasure5(),
                rec.getStrMeasure6(),
                rec.getStrMeasure7(),
                rec.getStrMeasure8(),
                rec.getStrMeasure9(),
                rec.getStrMeasure10(),
                rec.getStrMeasure11(),
                rec.getStrMeasure12(),
                rec.getStrMeasure13(),
                rec.getStrMeasure14(),
                rec.getStrMeasure15(),
                rec.getStrMeasure16(),
                rec.getStrMeasure17(),
                rec.getStrMeasure18(),
                rec.getStrMeasure19(),
                rec.getStrMeasure20(),
                rec.getStrSource());
    }
}
